//ConvertPrepare(xfrom,yfrom,zfrom,xto,yto,zto,view)

var mm;
cv_xfrom=argument0
cv_yfrom=argument1
cv_zfrom=argument2
cv_view=argument6
dX=argument3-argument0
dY=argument4-argument1
dZ=argument5-argument2
mm=sqrt(dX*dX+dY*dY+dZ*dZ)
dX/=mm
dY/=mm
dZ/=mm
uX=0
uY=0
uZ=1
mm=uX*dX+uY*dY+uZ*dZ
uX-=mm*dX
uY-=mm*dY
uZ-=mm*dZ
mm=sqrt(uX*uX+uY*uY+uZ*uZ)
uX/=mm
uY/=mm
uZ/=mm
tFOV=tan(camfov*pi/360)
uX*=tFOV
uY*=tFOV
uZ*=tFOV
vX=uY*dZ-dY*uZ
vY=uZ*dX-dZ*uX
vZ=uX*dY-dX*uY
vX*=view_wview[cv_view]/view_hview[cv_view]
vY*=view_wview[cv_view]/view_hview[cv_view]
vZ*=view_wview[cv_view]/view_hview[cv_view]
