// new_brick(x,y,z,xsize,ysize,zsize,color,alpha)
var brick;
brick = instance_create(0,0,obj_brick);
brick.x = argument0;
brick.y = argument1;
brick.z = argument2;
brick.xs = argument3;
brick.ys = argument4;
brick.zs = argument5;
brick.color = argument6;
brick.alpha = argument7;
brick.name = "brick"+string(global.brickCount);
brick.shape = "";
brick.rotation = 0;
brick.script = "";
brick.north = "";
brick.east = "";
brick.south = "";
brick.west = "";
brick.model = "";
brick.bound = GmnCreateBox(global.set,brick.xs,brick.ys,brick.zs,brick.xs/2,brick.ys/2,brick.zs/2);
brick.body = GmnCreateBody(global.set,brick.bound);
brick.light_range = 0;
brick.light_color = 0;
brick.collision = 1;
brick.isVisible = true;
ds_list_add(global.brickList,brick);
history_add("brick",brick);
global.brickCount += 1;
return brick;
